//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeHazVisto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetType
    {
        public int petTypeID { get; set; }
        public string PetTypeDescription { get; set; }
    }
}
